// import "./globals.css";
"use client";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navigation/NavBar";
const inter = Inter({ subsets: ["latin"] });
import { Provider } from "react-redux";
import store from "./store/store";

// export const metadata = {
//   title: "Di$count Finder",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <NavBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
